CC=g++

## put include path in CFLAGS
IDIR=
# CFLAGS=-c -Wall -I$(IDIR)
CFLAGS=-c -Wall

## put libs in LDFLAGS like -L/path/to/lib/ -l/lib name/
LDFLAGS=
LIBS = -lglut -lGLU -lGL

## Program's target name
TARGET = matrixmodelview

## Path for source codes and target file
SOURCEPATH = src
TARGETPATH = ./

## Put all cpp file to be compiled here
SOURCES = $(wildcard $(SOURCEPATH)/*.cpp)
OBJECTS = $(SOURCES:.cpp=.o)
EXECUTABLE = $(TARGETPATH)/$(TARGET)

.PHONY: all
all: $(SOURCES) $(EXECUTABLE)

## Each front @ is to hide the compilation line from the std output screen
$(EXECUTABLE) : $(OBJECTS)
	@echo Target problem \"$(TARGET)\" is stored in \"$(TARGETPATH)\"
	@$(CC) $(LDFLAGS) $(OBJECTS) -o $@ $(LIBS)

.cpp.o:
	@$(CC) $(CFLAGS) $< -o $@

.PHONY: clean
clean:
	@rm -rf $(EXECUTABLE) 
	@rm -f $(SOURCEPATH)/*.o 